# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7d6fc09dd760f3d0666198953485a4d686f43194c6cadc1e8383cebf0662abd8fcc006ebe2d4d89ac40abe08cb3f10b168e4a640165df4a63d075b958dff15

test:
  secret_key_base: 5a0648daec54b17ea1ec6ec006ae3b1450899032a8b07e73b4e04d7f945d5f9a2d0543af08f6c3a8f60776daf556e01123f272ae4f341880c734c0b612fff816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
